In [1]:
L = [123,432,457,234,-5434]

In [2]:
L

[123, 432, 457, 234, -5434]

In [4]:
import numpy as np

In [5]:
np.array(L) # Convierte una lista en un array

array([  123,   432,   457,   234, -5434])

In [7]:
a = np.array(L)
a

array([  123,   432,   457,   234, -5434])

In [8]:
b = np.array([12,43.2,True,'abc'])

In [9]:
b

array(['12', '43.2', 'True', 'abc'], dtype='<U32')

In [10]:
print(b)

['12' '43.2' 'True' 'abc']


In [11]:
# En un array no pueden haber diferente tipos de datos

In [12]:
L.pop()

-5434

In [13]:
L

[123, 432, 457, 234]

In [15]:
a.mean() # Media de la lista

-837.6

In [17]:
c = np.array([True,False])

In [18]:
c

array([ True, False])

---

In [19]:
L

[123, 432, 457, 234]

In [20]:
L[1:]

[432, 457, 234]

In [21]:
L[0:2]

[123, 432]

In [22]:
L[::2]

[123, 457]

---

In [23]:
a

array([  123,   432,   457,   234, -5434])

In [24]:
a[2:] # A diferencia de las lista, no se está creando otro array

array([  457,   234, -5434])

In [25]:
a[2:4]

array([457, 234])

In [26]:
b = a[2:4] # Se cre una vista de a

In [27]:
b

array([457, 234])

In [28]:
b[0]

457

In [29]:
b[:]

array([457, 234])

In [30]:
b

array([457, 234])

In [31]:
a

array([  123,   432,   457,   234, -5434])

In [32]:
b[:]=111

In [33]:
b

array([111, 111])

In [34]:
a

array([  123,   432,   111,   111, -5434])

In [35]:
# b modificó a a

In [36]:
c = a # Vista de a

In [37]:
c = a.copy() # Crea una copia de a

In [38]:
c[0] = 0

In [39]:
c

array([    0,   432,   111,   111, -5434])

In [40]:
a

array([  123,   432,   111,   111, -5434])