In [1]:
import numpy as np

In [2]:
mis_datos = np.arange(0,20)

In [3]:
print(mis_datos)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [4]:
np.reshape(mis_datos , (5,4)) # El default es opuesto a R.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [8]:
matr1 = np.reshape(mis_datos , (5,4) , order = 'C')
matr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [10]:
# Ejercicio: Llegar al número 9
matr1[2,1]

9

In [11]:
matr2 = np.reshape(mis_datos , (5,4) , order = 'F')
matr2

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [12]:
matr2[4,1]

9

In [13]:
# Concepto POO
# np.reshape(mis_dasots , (5,4))
type(mis_datos)

numpy.ndarray

In [14]:
mis_datos.reshape((5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

---

In [15]:
r1 = ["Soy" , "muy" , "sexy"]
r2 = ["Que" , "feo" , "eres"]
r3 = [1 , 2 , 3]

In [16]:
[r1 , r2 , r3]

[['Soy', 'muy', 'sexy'], ['Que', 'feo', 'eres'], [1, 2, 3]]

In [17]:
np.array([r1 , r2 , r3]) # <U$ menos de cuatro acaractéres

array([['Soy', 'muy', 'sexy'],
       ['Que', 'feo', 'eres'],
       ['1', '2', '3']], dtype='<U4')

In [18]:
print(np.array([r1 , r2 , r3]))

[['Soy' 'muy' 'sexy']
 ['Que' 'feo' 'eres']
 ['1' '2' '3']]


In [19]:
matr2[2]

array([ 2,  7, 12, 17])

In [20]:
matr2[:,2]

array([10, 11, 12, 13, 14])

In [23]:
matr2[0:3]

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17]])

In [24]:
matr2[0:2,2:5]

array([[10, 15],
       [11, 16]])

In [25]:
matr2[:,0:4]

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [26]:
matr2[:,0:2]

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [27]:
matr2[::2]

array([[ 0,  5, 10, 15],
       [ 2,  7, 12, 17],
       [ 4,  9, 14, 19]])

In [28]:
matr2[::2 , 1::2]

array([[ 5, 15],
       [ 7, 17],
       [ 9, 19]])